export const INPUTS_FILE_PATH = Symbol("INPUTS_FILE_PATH");
export const INPUTS_TRANSFORMED_FILE_PATH = Symbol("INPUTS_TRANSFORMED_FILE_PATH");
export const INPUTS_MAX_ITEMS = Symbol("INPUTS_MAX_ITEMS");

